### ISSUE TITLE
Kubernetes Node, Storage , and System level cluster role compliance is missing

### ISSUE THREAD

**Issue by vishu184** [turbot/steampipe-mod-kubernetes-compliance#89]
**Is your feature request related to a problem? Please describe.**
In Kubernetes mods we do not have any compliance available for Node, Storage and system cluster role.

**Comment by misraved** [comment]
Welcome to Steampipe @vishu184 👍!!

Apologies for the radio silence on this issue.

We do have a few controls defined in https://github.com/turbot/steampipe-mod-kubernetes-compliance/blob/main/controls/role.sp that primarily address the roles.

As a part of our implementation, we focussed on getting the control coverage for CIS and NSA benchmarks. Is there a specific compliance that you are looking out for?

**Comment by misraved** [comment]
Hi @vishu184,

I hope all is well with you. I'm writing to follow up on this issue. Since we haven't received any updates or feedback from you in a while, we'll be closing this issue for now.

If you still need assistance or if you have any further questions, please feel free to reopen the issue or create a new one. We're always here to help!

Thank you for your understanding.
